services:
  docs:
    image: d3_chart_local_docs
    container_name: d3_chart_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./d3_chart:/app/d3_chart:z
    ports:
      - '9000:9000'
    command: /start-docs

