version: "3.9"

x-common-restart-policy: &common-restart-policy "no"

services:

  postgres-db:
    image: postgres:16
    container_name: d3_chart_postgres_db
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    network_mode: "host"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: *common-restart-policy

  d3-chart-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: d3_chart_server
    env_file:
      - .env
    volumes:
      - ./:/app
#    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: ./run_server.sh
    network_mode: "host"
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: *common-restart-policy
